name: ascii_workflow

on: push
jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v4
            - name: install cowsay
              run: sudo apt-get install cowsay -y && sudo apt-get install cowsay-off -y
            - name: Execute cowsay CMD
              run: cowsay -f dragon "im king of jungal" >> dragon.txt
            - name: check dragon file exists or not
              run: grep -i "dragon" dragon.txt
            - name: reading dragon file
              run: cat dragon.txt
            - name: list repo files
              run: ls -lrta
            
