name: ascii_workflow

on: push
jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v4
            - name: install cowsay
              run: sudo apt-get install cowsay -y && sudo apt-get install cowsay-off -y
            - name: Execute cowsay CMD
              run: cowsay -f lion "im king of jungal" >> lion.txt
            - name: check lion file exists or not
              run: grep -i "lion" lion.txt
            - name: reading lion file
              run: cat lion.txt
            - name: list repo files
              run: ls -lrta
            
