name: first_workflow

on: push
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome_message
              run: echo "my first github action job"
            - name: list_files
              run: ls
            - name: read_files
              run: cat README.md
