name: first_workflow

on: push
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: git__checkout
              uses: actions/checkout@v4
            - name: List and read files
              run: |
                  echo "my first github action job"
                  ls -ltra
                  cat README.md
            - name: Generate a ASCII art work
              run: cowsay -f dragon "run for cover im a dragon" >> dragon.txt
            # - name: list_files
            #   run: ls
            # - name: read_files
            #   run: cat README.md
