name: multi job ascii

on: push

jobs:
    packages_Installation:
        runs-on: ubuntu-latest
        steps:
            - name: updating packages
              run: sudo apt update -y
            - name: Install cowsay 
              run: sudo apt-get install cowsay -y
            - name: Execute cowsay CMD
              run: cowsay -f dragon "shaktishali dragon bayataki ra" >> dragon.txt
            - name: upload the dragon
              uses: actions/upload-artifact@v4
              with:
                name: dragon
                path: dragon.txt
    
    checking_files:
        runs-on: ubuntu-latest
        needs: packages_Installation
        steps:
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: dragon
          
          - name: check for dragon
            run: grep -i "dragon" dragong.txt
    
    reading_dragon:
        needs: checking_files
        runs-on: ubuntu-latest
        steps:
          - name: download artifact
            uses: actions/download-artifact@v4
            with:
              name: dragon
          - name: reading dragon
            run: cat dragon.txt
