name: multi job ascii

on: push

jobs:
    packages_Installation:
        runs-on: ubuntu-latest
        steps:
            - name: updating packages
              run: sudo apt update -y
            - name: Install cowsay 
              run: sudo apt-get install cowsay -y
            - name: Execute cowsay CMD
              run: cowsay -f dragon "shaktishali dragon bayataki ra" >> dragon.txt
            - name: Sleep for 30 seconds
              run: sleep 30
    
    checking_files:
        runs-on: ubuntu-latest
        steps:
          - name: sleep for 10 seconds
            run: sleep 10
          - name: check for dragon
            run: grep -i "dragon" dragong.txt
    
    reading_dragon:
        runs-on: ubuntu-latest
        steps:
          - name: reading dragon
            run: cat dragon.txt
