name: shell scripting

on: push
jobs: 
    scripting:
        runs-on: ubuntu-latest
        steps:
            - name: git checkout
              uses: actions/checkout@v4
            - name: listing files
              run: ls -ltra
            - name: running shell script
              run: |
                 chmod +x ascii.sh
                 ./ascii.sh  
