# name: variables
# on: push
# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - name: building docker image
#               env:
#                   CONTAINER_REGISTRY: docker.io
#                   DOCKER_USERNAME: neo
#                   IMAGE_NAME: my_dragon
#               run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/${{env.IMAGE_NAME}}:latest
#             - name: docker login
#               env:
#                 DOCKER_USERNAME: neo
#                 DOCKER_PASSWORD: 0912873465
#               run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}
#             - name: docker publish
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: neo
#                 IMAGE_NAME: my_dragon
#               run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}
#     Deploy:
#         runs-on: ubuntu-latest
#         needs: build
#         steps:
#           - name: docker run
#             env: 
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: neo
#                 IMAGE_NAME: my_dragon
#             run: echo docker run --name my_dragon -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

name: variables
on: push
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: neo
  IMAGE_NAME: my_dragon
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: building docker image
              run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/${{env.IMAGE_NAME}}:latest
            - name: docker login
              env:
                DOCKER_PASSWORD: 0912873465
              run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}
            - name: docker publish
              run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}
    Deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: docker run
            run: echo docker run --name my_dragon -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

